# Generated by Django 4.0 on 2021-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Sender', models.CharField(max_length=50)),
                ('Name_Of_Receiver', models.CharField(max_length=50)),
                ('Transfer_Amount', models.IntegerField()),
                ('Sender_Updated_Balance', models.IntegerField()),
                ('Receiver_Updated_Balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('current_credits', models.IntegerField()),
                ('mail_id', models.EmailField(default=False, max_length=254)),
                ('Phone_num', models.IntegerField()),
            ],
        ),
    ]
